### PR TITLE
Work towards a 2.0 release

### PR DESCRIPTION
**Pull request by ajdawson**
This is most of the things I can think of that need doing. Replacing the build system is essential for continued distribution of the package. The new CI workflows are intended to replace the previously inactive ones, so testing of pull requests etc. works again. Documentation is revised so it builds with latest sphinx. Perhaps most significant is removal of cdms interface due to lack of support for the backend cdms2 package.

### CODE REVIEW

**Comment by donehii** [comment]
well，the old one documentation page has gone ?

**Comment by ajdawson** [comment]
Yes, it was replaced with the new one. Not a lot changed though so hopefully not important.

**Comment by donehii** [comment]
yea, I've updated to 2.0，usage is the same. en，There is a question puzzling me now， I found the divergence caculated by Metpy and Windspharm are quite a different from each other, I wish I have done the right way. So, is that true? If it is，would you mind to tell me why for this? or how can I find the answer to take metpy or the windspharm in my situation。 Longing for your reply，Thanks a lot !

---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 11/21/2024 17:56 |
| To | ajdawson/windspharm ***@***.***> |
| Cc | DoneX ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [ajdawson/windspharm] Work towards a 2.0 release (PR #130) |

Yes, it was replaced with the new one. Not a lot changed though so hopefully not important.

**Comment by ajdawson** [comment]
Please open a new issue with more details if you wish to discuss the divergence calculation in more detail. You will need to provide an example of what you did, and how the results differ.

**Pull request merged**
